### ISSUE TITLE
Pimatic not starting when coc activated in config.json

### ISSUE THREAD

**Issue by ikewestbrook** [dfischbach/pimatic-coc#1]
Hi there,

i got the strange problem when i configure coc plugin in config.json and restart pimatic no connection can be established anymore.
Any ideas, how this can happen?

Like this:

{
      "plugin": "coc",
      "hardwareType": "CUL",
      "serialDeviceName": "/dev/mmcblk0p2"
    }

When added to config without hardwareType & serialDeviceName pimatic works fine.
Thanks!

**Comment by dfischbach** [comment]
Hello Kay,

sorry for the delayed response, I’ve been busy during the last days.
Can you give me some more informations:
Did you used the plugin the first time or was it already working and suddenly stopped?
What version  of pimatic you are using?
Did you enabled debug output and are you seeing any messages?

Regards,
Dirk

**Comment by ikewestbrook** [comment]
Hi Dirk, no worries! :+1: 

i run the latest and greatest version of pimatic. Every plugin is also up-to-date. As a device i conntected a busware cul v3 stick as shown here.
http://busware.de/tiki-index.php?page=CUL
When i entered the above settings and restart pimatic, i'm losing connection to pimatic, forcing me to correcting the config file via ssh. There is non in the logs.
Any ideas?

Thanks. Kay.

**Comment by ikewestbrook** [comment]
Seems that i got it to work now with restarting the raspberrypi. Here are the log entries.
info [pimatic-coc]: open serialPort /dev/ttyAMA0
17:46:35info [pimatic-coc]: init coc end
17:46:33info [pimatic-coc]: init coc begin
17:46:33info [pimatic-coc]: coc: init with serial device name /dev/ttyAMA0@38400, hardwareType COC
17:46:33info [pimatic-coc]: coc: init

Does that look ok?

I'm planning to integrate this device.

http://www.elv.de/fs20-hgs-funk-hygrostat-inkl-batterien.html
