### ISSUE TITLE
Intertechno Devices controllable?

### ISSUE THREAD

**Issue by ikewestbrook** [dfischbach/pimatic-coc#4]
Hi,
thanks for the plugin. 

I'm operating a 
http://busware.de/tiki-index.php?page=CUL-V2
device with my Raspberrypi 3.

Would it be possible with this plugin to control these Intertechno devices?
https://www.amazon.de/dp/B0054IPASK?tag=pimatic-21

Many thanks. Kay.

**Comment by dfischbach** [comment]
Hello Kay,

to control the Intertechno devices you need at least the 433MHz Version, the 868MHz will not work.
Further it depends on the devices itself. Most have DIP switches for fixed addresses. Some of them don’t have switches. They use a rolling code which may not work with COC/CUL.

if you want to experiment with the CUL consult the command reference. Use a serial monitor to send IT xxxxx xx xx like commands to control Intertechno devices.
If you have found the right commands you can enter them in the config file like this
  "devices": [
    {
      "class": "COCSwitch",
      "id": "socket2",
      "name": "Socket 2",
      "commandOn": „ITxxxxxx",
      "commandOff": „ITyyyyyy"
    }
  ],

I’m using the Homeduino plugin with an Arduino nano to control the my Intertechno devices. This combination works best for me with a lot of different devices and is widely supported. I’m also using a more expansive sender/receiver, which results in control range from out of the basement of my house to the outer edges of the garden.

Regards,
Dirk

**Comment by ikewestbrook** [comment]
Hi Dirk,

thanks for your detailed reply.
I'll start to experiment based on your thoughts.

Would love to use a homeduino. However i'm not too much into soldering. :-) 
Do you know any good step by step tutorial to build and run one?

Many thanks. Kay.

**Comment by ikewestbrook** [comment]
I have organized myself 3 elro socket switches and tried to integrate them into a homematic environment using CUxD and a busware cul v3. 

By sending device specific commands through the cuxd terminal i was able to switch the state of the socket. Example: is0F0F0F0FFFFF0

So this seems to work just great!

Is there a way i can get this to run with your plugin? Config looks like this, however does nothing. :-)

    {
      "class": "COCSwitch",
      "id": "lamp-eg",
      "name": "lamp-eg",
      "commandOn": "is0F000F0FFFFF",
      "commandOff": "is0F000F0FFFF0",
      "hap": {
        "service": "Switch",
        "exclude": false
      }
    }, 

The CUL seems to be recognized fine.

**Comment by dfischbach** [comment]
Do you have also configured the plugin itself as explained here: https://github.com/dfischbach/pimatic-coc? hardwareType and serialDeviceName must be set right.
Please set the loglevel to debug, restart pimatic and check the messages for coc plugin messages.

**Comment by ikewestbrook** [comment]
Yap, i did. 

Plugin Config

```
    {
      "plugin": "coc",
      "hardwareType": "CUL",
      "serialDeviceName": "/dev/ttyAMA0"
    },
```

Device Config

```
 {
   "class": "COCSwitch",
   "id": "lamp-eg",
   "name": "lamp-eg",
   "commandOn": "is0F000F0FFFFF",
   "commandOff": "is0F000F0FFFF0",
   "hap": {
     "service": "Switch",
     "exclude": false
   }
 },
```

Debug Output
```
 info [pimatic-coc]: open serialPort /dev/ttyAMA0
 19:56:01info [pimatic-coc]: coc: init with serial device name /dev/ttyAMA0@38400, hardwareType CUL
 19:56:01info [pimatic-coc]: coc: init
```

There isnt anymore info in the log.

**Comment by dfischbach** [comment]
ttyAMA0 is the internal serial port of the pi. You need to find the serial port of the USB device.
Use dmesg | grep tty and look for ttyUSBx. Update your config, restart.

**Comment by ikewestbrook** [comment]
That did the trick! :-) Many thanks!
